heron/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path as url

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views.generic.base import RedirectView
from vfwheron import views as vfw_views
from django.views.i18n import JavaScriptCatalog

# TODO: for JS translations see:
#  https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#note-on-performance
urlpatterns = [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^$', RedirectView.as_view(url='home/', permanent=False)),
    path('home/', include('vfwheron.urls')),
    path('admin/', admin.site.urls),
    path('legals', vfw_views.Legals.as_view(), name='legals'),
    path('workspace/', include('wps_gui.urls', namespace='wps_gui')),
    path('monitor/', include('heron_monitor.urls', namespace='heron_monitor')),
    path('visual/', include('heron_visual.urls', namespace='heron_visual')),
    path('upload/', include('upload.urls', namespace='upload')),
    path('download/<str:name>', vfw_views.DownloadView.as_view()),
    path('admin/doc/', include('django.contrib.admindocs.urls')),  # from wps_workflow
    path('user/', include('author_manage.urls', namespace='author_manage')),
    # path('__debug__/', include(debug_toolbar.urls))  # only when debug toolbar is installed!
]

handler404 = 'vfwheron.views.error_404_view'

# This is just to test the upload in the development environment
if settings.DEBUG and settings.DEBUG != '':
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

heron_upload/urls.py
from django.conf.urls import include
from django.urls import re_path as url

from heron_upload import views
from . import views

app_name = 'upload'

service_urls = [
]

urlpatterns = [
    # url(r'^$', views.home, name='home'),
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^clear/$', views.clear_database, name='clear_database'),
    url(r'^clear/(?P<pk>\d+)/delete/$', views.delete_data, name='delete_data'),
    url(r'^(?P<service>\w+)/', include(service_urls)),
    url(r'^heron-upload/$', views.HomeView.as_view(), name='heron_upload'),
]

heron_upload/models.py
from django.contrib.gis.db import models


class UploadedFile(models.Model):
    title = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to='uploads/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

heron_upload/forms.py
from django import forms

# To upload the file to a model check the django documentation
# https://docs.djangoproject.com/en/1.11/topics/http/file-uploads/
# 
class MultiUploadFileForm(forms.Form):
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={
        'multiple': True, 
        'id': 'select_data_button',
        'style': 'display: none',
        'onchange': "this.form.submit()",
        }), label='')

from .models import UploadedFile

class UploadForm(forms.ModelForm):
    class Meta:
        model = UploadedFile
        fields = ('file', )

heron_upload/views.py
from django.shortcuts import render
from django.views import View

from django.views.generic import TemplateView
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from heron_upload.forms import UploadForm
from heron_upload.models import UploadedFile


# def home(request):
#     """
#     Dummy page for Heron Upload tool.
#     """
#     return render(request, 'heron_upload/home.html')


class HomeView(TemplateView):
    template_name = 'heron_upload/home.html'

    def get(self, request):
        data_list = UploadedFile.objects.all()
        return render(self.request, 'heron_upload/home.html', {'data': data_list})

    def post(self, request):
        form = UploadForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            file = form.save()
            data = {'is_valid': True, 'name': file.file.name, 'url': file.file.url}
        else:
            data = {'is_valid': False}
        return JsonResponse(data)


def clear_database(request):
    for file in UploadedFile.objects.all():
        file.file.delete()
        file.delete()
    return redirect(request.POST.get('next'))


def delete_data(request, pk):
    data = get_object_or_404(UploadedFile, pk=pk)
    print('in delete / data: ', data)
    if request.method == 'POST':
        form = UploadForm(request.POST, instance=data)
    else:
        form = UploadForm(instance=data)
    return HomeView.get(request)

    for file in UploadedFile.objects.all():
        file.file.delete()
        file.delete()
    return redirect(request.POST.get('next'))

 # class DataUploadView(View):
 #     def get(self, request):
 #         data_list = UploadedFile.objects.all()
 #         return render(self.request, 'base_app/workspace.html', {'data': data_list})

heron_upload/templates/heron_upload/home.html
<meta charset="UTF-8">


{% extends "vfwheron/base.html" %}

{% load static %}

<head>
{#    <script src="{% static 'vfwheron/js/jquery-3.2.1.min.js' %}"></script>#}
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    {# JQUERY FILE UPLOAD SCRIPTS #}
    <script src="{% static 'heron_upload/js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
    <script src="{% static 'heron_upload/js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
    <script src="{% static 'heron_upload/js/jquery-file-upload/jquery.fileupload.js' %}"></script>

    <script src="{% static 'heron_upload/js/data_access.js' %}"></script>
</head>
<body>
{% block title %}- Heron Upload{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1>Upload</h1>
            <p>Diese Seite befindet sich noch im Aufbau</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">

            <h4>Bisher ist noch kein Upload verfügbar.</h4>

        </div>
    </div>

    <!-- Here we only offer the upload button to access data.
    Please be aware that uploading data is a security issue that you have to handle yourself.
    Django stores data up to 2.5 megabyte in memory, bigger files in a tmp folder. For details see
    https://docs.djangoproject.com/en/1.11/topics/http/file-uploads/#where-uploaded-data-is-stored
    Some ideas (in German) about uploading data (and why you shouldn't offer that) are
    available at https://wiki.selfhtml.org/wiki/PHP/Anwendung_und_Praxis/File_Upload
    The better choice for offering data would be a database. -->

    <div>
        {# create a button pointing to an invisible input button: #}
        <hr style="margin-bottom: 0px;">
        <i class="respo-padding fa fa-upload fa-fw"></i>
        <button type="button" class="btn btn-primary js-upload-photos">Upload
            data
        </button>
        <!-- call js function for upload and (invisible) input button
    id is the same as defined in data_access.js -->
        <input id="fileupload" type="file" name="file" multiple
               style="display: none;"
               data-url="{% url 'upload:heron_upload' %}"
               data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
    </div>


{% endblock %}
</body>