author_manage/urls.py
from django.urls import path
# from author_manage import views
from django.urls.conf import re_path
from author_manage.admin import resource_manager
from author_manage.admin import user_manager
from author_manage.views import *

# for security reasons all urls are accessible only for logged in users

app_name = 'author_manage'  # jm

urlpatterns = [

    # entry point to the web site, home page
    path('', HomeView.as_view(), name='home'),

    # pages, accessible only for the admin - for managing resources/users
    re_path(r'^resource-manager/', resource_manager.urls),
    re_path(r'^user-manager/', user_manager.urls),

    # profile page, where the user can change his name/see his current access requests
    # the admin can additionally see his current deletion requests
    re_path(r'^profile/$', ProfileView.as_view(), name='profile'),

    # subpage of the profile page, where the user can see all the resources that he owns
    re_path(r'^profile/my-resources/$', MyResourcesView.as_view(), name='my-resources'),

    # for every resource that a user owns, he has the option to edit its permissions
    # initially only the users that have ANY permissions about this resource are displayed
    re_path(r'^profile/my-resources/(?P<resourceid>\d+)-edit-users-permissions/$', PermissionEditingView.as_view(),
            name='edit permissions'),

    # the user has also the option to search for a user, who does not have any permission about
    # this resource to this point, and grant him such
    re_path(r'^profile/my-resources/(?P<resourceid>\d+)-edit-users-permissions/search$',
            PermissionEditingViewSearch.as_view(), name='edit permissions searching for user'),

    # subpage for adding a new resource
    re_path(r'^profile/my-resources/add-new-resource/$', AddNewResourceView.as_view(), name='add-new-resource'),

    # subpage for editing first and/or last name; can not be null
    re_path(r'^profile/edit-name/$', EditNameView.as_view(), name='edit-name'),

    # page for displaying all resources in the portal
    # the user sees 'access' button only if he is privileged to access the resource
    # otherwise he has the option to send an access request
    re_path(r'^resources-overview/$', ResourcesOverview.as_view(), name='resources-overview'),

    # search function in case the resources in the portal are too many
    re_path(r'^resources-overview/search$', ResourcesOverviewSearch.as_view(), name='search-resources'),

    # url for accessing a resource (download function)
    re_path(r'^resources/(?P<resourceid>\d+)$', OpenResourceView.as_view(), name='open resources'),

    # urls for sending/canceling an access request
    re_path(r'^send-access-request/(?P<resourceid>\d+)$', SendAccessRequestView.as_view(), name='send-access-request'),
    re_path(r'^cancel-access-request/(?P<resourceid>\d+)$', CancelAccessRequest.as_view(),
            name='cancel-access-request'),

    # urls for approving/denying an access request; accessible only if requestid
    # is valid and the current user has rights too handle the request
    re_path(r'^approve-access-request/(?P<requestid>\d+)$', ApproveAccessRequest.as_view(),
            name='approve-access-request'),
    re_path(r'^deny-access-request/(?P<requestid>\d+)$', DenyAccessRequest.as_view(), name='deny-access-request'),

    # urls for sending/canceling a deletion request
    re_path(r'^send-deletion-request/(?P<resourceid>\d+)$', SendDeletionRequestView.as_view(),
            name='send-delete-request'),
    re_path(r'^cancel-deletion-request/(?P<resourceid>\d+)$', CancelDeletionRequestView.as_view(),
            name='cancel-delete-request'),

    # urls for approving/denying a deletion request; accessible only if requestid
    # is valid and the current user has rights too handle the request
    re_path(r'^approve-deletion-request/(?P<requestid>\d+)*$', ApproveDeletionRequest.as_view(),
            name='approve deletion request'),
    re_path(r'^deny-deletion-request/(?P<requestid>\d+)$', DenyDeletionRequest.as_view(),
            name='deny deletion request'),

    # url for deleting a resource, accessible only for the admin
    re_path(r'^delete-resource/(?P<resourceid>\d+)*$', DeleteResourceView.as_view(), name='delete resource'),

]

heron/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path as url

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views.generic.base import RedirectView
from vfwheron import views as vfw_views
from django.views.i18n import JavaScriptCatalog

# TODO: for JS translations see:
#  https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#note-on-performance
urlpatterns = [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^$', RedirectView.as_view(url='home/', permanent=False)),
    path('home/', include('vfwheron.urls')),
    path('admin/', admin.site.urls),
    path('legals', vfw_views.Legals.as_view(), name='legals'),
    path('workspace/', include('wps_gui.urls', namespace='wps_gui')),
    path('monitor/', include('heron_monitor.urls', namespace='heron_monitor')),
    path('visual/', include('heron_visual.urls', namespace='heron_visual')),
    path('upload/', include('upload.urls', namespace='upload')),
    path('download/<str:name>', vfw_views.DownloadView.as_view()),
    path('admin/doc/', include('django.contrib.admindocs.urls')),  # from wps_workflow
    path('user/', include('author_manage.urls', namespace='author_manage')),
    # path('__debug__/', include(debug_toolbar.urls))  # only when debug toolbar is installed!
]

handler404 = 'vfwheron.views.error_404_view'

# This is just to test the upload in the development environment
if settings.DEBUG and settings.DEBUG != '':
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

author_manage/forms.py
from django import forms
from .models import Resource

class AddNewResourceForm(forms.ModelForm):
    """

    """
    class Meta:
        model = Resource
        fields = ("type", "link")
        # fields = ("name", "type", "description", "link")

    def __init__(self, *args, **kwargs):
        """

        @param args:
        @type args:
        @param kwargs:
        @type kwargs:
        """
        super(AddNewResourceForm, self).__init__(*args, **kwargs)
        # self.fields['name'].widget.attrs.update({'class': 'new-res-name', 'placeholder': 'max 150 characters'})
        self.fields['type'].widget.attrs.update({'class': 'new-res-type', 'placeholder': 'max 50 characters'})
        # self.fields['description'].widget.attrs.update({'class': 'new-res-description',
        #                                                 'placeholder': 'max 250 characters'})
        self.fields['link'].widget.attrs.update({'class': 'new-res-link'})

author_manage/views.py
import logging

from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect  #, _get_queryset  # , render_to_response
from django.template.loader import render_to_string
from django.views import generic
from django.contrib.auth.decorators import login_required
from author_manage.models import *
from django.core.files import File
from django.conf import settings
import os
from django.utils.decorators import method_decorator

from vfwheron.models import Details
from .filters import PersonsFilter, DetailsFilter
from .forms import AddNewResourceForm
from django.template.context_processors import csrf
from . import utilities
from django.http import Http404
from django.core.mail.message import EmailMultiAlternatives
from django.utils.html import strip_tags
from django.core.exceptions import PermissionDenied, ValidationError
from _csv import reader, Error
import mimetypes
# from test.support import resource
from django.db.models import Q
from django.views.decorators.cache import never_cache
from django.shortcuts import get_object_or_404
from django.contrib import messages

from itertools import chain
from author_manage.models import Resource
from author_manage.apps import authorManageConfig

logger = logging.getLogger(__name__)


@receiver(user_logged_in)  # function to collect user data - especially resources - on login
def get_user_embargo_resources(request, user, **kwargs):
    maintainer_set = Resource.objects.filter(maintainers=user, dataEntry__embargo=True)
    reader_set = Resource.objects.filter(readers=user, dataEntry__embargo=True)
    owner_set = Resource.objects.filter(owners=user, dataEntry__embargo=True)
    datasets = reader_set | maintainer_set | owner_set
    request.session['datasets'] = list(datasets.values_list('dataEntry_id', flat=True))


# TODO: document
@method_decorator(login_required, name='dispatch')
class HomeView(generic.View):
    """

    """
    model = User
    def get(self, request):
        """

        @param request:
        @type request:
        @return:
        @rtype:
        """
        is_admin = request.user.is_staff
        return render(request, 'author_manage/home.html', {'is_admin': is_admin})


# @method_decorator(never_cache, name='dispatch')
@method_decorator(login_required, name='dispatch')
class ProfileView(generic.ListView):
    """

    """
    model = AccessRequest.objects.none()
    template_name = 'author_manage/profile.html'
    context_object_name = 'requests_list'
    paginate_by = 4

    def get(self, request):
        """

        @param request:
        @type request:
        @return:
        @rtype:
        """
        current_user = self.request.user
        resources = MyResourcesView.get_queryset(self)

        # load access requests if user owns any resources
        if resources.exists():
            self.model = AccessRequest.objects.filter(resource__in=resources)

        # load all deletion request if user is staff
        if self.model.exists():
            if current_user.is_staff and DeletionRequest.objects.all().exists():
                self.model = get_sorted_requests(self.model, DeletionRequest.objects.all().order_by('-creationDate'))
                # self.model = list(chain(self.model,DeletionRequest.objects.all()))
        else:
            if current_user.is_staff and DeletionRequest.objects.all().exists():
                self.model = DeletionRequest.objects.all().order_by('-creationDate')

        return super(ProfileView, self).get(request)

    def get_queryset(self):
        """

        @return:
        @rtype:
        """
        return self.model

    def get_context_data(self, **kwargs):
        """

        @param kwargs:
        @type kwargs:
        @return:
        @rtype:
        """
        context = super(ProfileView, self).get_context_data(**kwargs)
        context['is_admin'] = self.request.user.is_staff
        return context


# the view for showing all the user's resources
@method_decorator(never_cache, name='dispatch')
@method_decorator(login_required, name='dispatch')
class MyResourcesView(generic.ListView):
    """

    """
    model = Resource
    template_name = 'author_manage/my-resources.html'
    deletion_requested = Resource.objects.none()

    def get_queryset(self):
        """

        @return:
        @rtype:
        """
        owner_set = Resource.objects.filter(owners=self.request.user)
        maintainer_set = Resource.objects.filter(maintainers=self.request.user)
        reader_set = Resource.objects.filter(readers=self.request.user)
        deletion_set = Resource.objects.filter(deletionrequest__sender=self.request.user)
        access_set = Resource.objects.filter(accessrequest__sender=self.request.user)
        # What about:
        # users = User.objects.all().select_related('profile')
        current_user = owner_set | maintainer_set | reader_set | deletion_set | access_set
        return current_user.all()

    # returns a dictionary representing the template context.
    def get_context_data(self, **kwargs):
        """

        @param kwargs:
        @type kwargs:
        @return:
        @rtype:
        """
        context = super(MyResourcesView, self).get_context_data(**kwargs)
        context['deletion_requested'] = Resource.objects.filter(
            id__in=DeletionRequest.objects.filter(sender=self.request.user).values('resource_id'))
        context['is_admin'] = self.request.user.is_staff
        return context


# the view for sending a deletion request
@method_decorator(never_cache, name='dispatch')
@method_decorator(login_required, name='dispatch')
class SendDeletionRequestView(generic.View):
    """

    """

    def post(self, request, *args, **kwargs):
        """

        @param request:
        @type request:
        @param args:
        @type args:
        @param kwargs:
        @type kwargs:
        @return:
        @rtype:
        """
        pk = self.kwargs['resourceid']  # get the id of the resource which is included in the url

        try:
            res = Resource.objects.get(id=pk)
        except Resource.DoesNotExist:
            # redirects the current user to profile/my-resources if a resource with such an id does not exist
            logger.info(
                "User %s tried to send a deletion request for non-existing resource \n" % request.user.username)
            raise Http404()

        # raises the PermissionDenied exception if the current user has no ownership for this resource
        if not res.owners.filter(id=request.user.id).exists():
            logger.info("User %s tried to send a deletion request for resource '%s' without being an owner! \n" %
                        (request.user.username, res.name))
            raise PermissionDenied
        # redirects the current user to profile/my-resources if the user is a staff user or the user has already
        # requested to delete the resource
        if request.user.is_staff or DeletionRequest.objects.filter(resource=res, sender=request.user).exists():
            logger.info("User %s tried to inconsistently send a deletion request for resource '%s' \n" %
                        (request.user.username, res.name))
            # return redirect("/profile/my-resources")
            return redirect('author_manage:my-resources')

        # creates a deletion request with the given description
        req = DeletionRequest.objects.create(sender=request.user,
                                             resource=Resource.objects.get(id=pk),
                                             description=request.POST['descr'])
        message = req.description

        # notifies all the staff users
        html_content = render_to_string('author_manage/mail/delete-resource-request-mail.html',
                                        {'user': request.user, 'resource': req.resource,
                                         'request': req, 'message': message})
        text_content = strip_tags(html_content)
        email_to = [x[0] for x in CustomUser.objects.filter(is_staff=True).values_list('email')]
        email_from = request.user.email
        msg = EmailMultiAlternatives('Request for deletion of a resource', text_content, email_from, email_to)
        msg.attach_alternative(html_content, "text/html")
        msg.send()
        logger.info("Deletion request for '%s' resource was sent by %s \n" % (res.name, request.user.username))
        logger.info("An email was sent to the Staff members from %s, Subject: Deletion Request for '%s' \n" %
                    (request.user.username, res.name))
        # return redirect("/profile/my-resources")
        return redirect('author_manage:my-resources')


# the view for canceling a deletion request
@method_decorator(never_cache, name='dispatch')
@method_decorator(login_required, name='dispatch')
class CancelDeletionRequestView(generic.View):
    """

    """

    def post(self, request, *args, **kwargs):
        """

        @param request:
        @type request:
        @param args:
        @type args:
        @param kwargs:
        @type kwargs:
        @return:
        @rtype:
        """
        pk = self.kwargs['resourceid']  # get the id of the resource which is included in the url

        try:
            res = Resource.objects.get(id=pk)
        except Resource.DoesNotExist:
            # redirects the current user to the 404 if a resource with such an id does not exist
            logger.info(
                "User %s tried to cancel a deletion request for non-existing resource \n" % request.user.username)
            raise Http404()

        # raises the PermissionDenied exception if the current user has no ownership for this resource
        if not res.owners.filter(id=request.user.id).exists():
            logger.info("User %s tried to cancel a deletion request for resource '%s' without being an owner! \n" %
                        (request.user.username, res.name))

author_manage/templates/author_manage/add-new-resource.html
<!-- template for add-new-resource page -->
{% extends "author_manage/profile.html" %}

{% block styles %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'author_manage/css/profile.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'author_manage/css/my-resources.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'author_manage/css/add-new-resource.css' %}" />
{% endblock %}

{% block requests_or_resources %}
  <h1>This page is still under construction and has no function.</h1>
<div class="mini-nav">
   <a href="{% url 'author_manage:profile' %}"
      class="noncurrent w3-btn w3-blue"><strong>Requests</strong></a></li>
   <a href="{% url 'author_manage:profile' %}my-resources"
      class="current w3-btn w3-blue"><strong>My Resources</strong></a></li>
</div>
<div class="add-res">
   <form action = "" method="post" enctype="multipart/form-data" class="add-res-form">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="add w3-btn w3-blue">Add</button>
   </form>
</div>
{% endblock %}

{% block wizard %}
{% endblock %}

author_manage/templates/author_manage/base.html
<meta charset="UTF-8">
{% extends "vfwheron/base.html" %}

{% block content %}

      {% block body %}
      {% endblock %}
{% endblock %}

author_manage/templates/author_manage/home.html
<!-- home page template -->

{% extends "author_manage/base.html" %}

{% block styles %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'author_manage/css/base.css' %}" />
{% endblock %}

{% block home%}
class="active";
{% endblock %}

{%block body%}
{% endblock %}

author_manage/templates/author_manage/my-resources.html
<!-- profile subpage which displays all the resources owned by the current user -->

{% extends "author_manage/profile.html" %}

{% block styles %}
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'author_manage/css/modal-dialog-info.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'author_manage/css/modal-dialog-req.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'author_manage/css/profile.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'author_manage/css/my-resources.css' %}"/>
{% endblock %}

{% block requests_or_resources %}
  <div class="mini-nav">
    <a href="{% url 'author_manage:profile' %}" class="noncurrent w3-btn w3-blue"><strong>Requests</strong></a></li>
    {#       class="noncurrent"#}
    {#    <a href="{% url 'author_manage:profile' %}my-resources" class="current">My Resources</a></li>#}
  </div>

  <div class="resources-container">
    <!-- adding new resource -->
    <a href="{% url 'author_manage:profile' %}my-resources/add-new-resource"
       class="create-resource w3-btn w3-blue" title="Add new resource">
      <i class="fa fa-plus"></i></a>
    <br>

    <!-- if the user does not own any resources -->
    {% if not resource_list %}
      <p class="body"> Currently no resources. </p>
    {% endif %}

    {% for resource in resource_list %}
      <p>
      <table>

        <tr>
          <th colspan="2">
            <a href="#{{ resource.id }}" class="res-name"> {{ resource.dataEntry.title }} </a>
          </th>
          {% comment %}<th>
                <!-- modal dialog showing meta info about the resource and an access button -->
                <div id="{{ resource.id }}" class="modalDialog">
                  <a href="" title="Close" id="x"> x </a>
                  {#         <h2 id="details">Details</h2>#}
                  <br>
                  {#         <p>Name: <strong>{{resource.name}}</strong></p>#}
              </th>{% endcomment %}
        <tr>
          <td>Abstract:</td>
          <td>{{ resource.dataEntry.abstract }}</td>
          {#              <td><strong>{{ resource.dataEntry }}</strong></td>#}
        </tr>
        <tr>
          {% if resource.dataEntry.latest_version %}
            <td>Version (latest):</td>
            <td>{{ resource.dataEntry.version }} ({{ resource.dataEntry.latest_version }})</td>
          {% else %}
            <td>Version:</td>
            <td>{{ resource.dataEntry.version }}</td>
          {% endif %}
        </tr>
        <tr>
          <td>Comment:</td>
          <td>{{ resource.dataEntry.comment }}</td>
        </tr>
        <tr>
          <td>License:</td>
          <td title="{{ resource.dataEntry.license.link }}">
            {{ resource.dataEntry.license }}</td>
        </tr>
        <tr>
          <td>Variable (Symbol) [Unit]:</td>
          <td>{{ resource.dataEntry.variable }}</td>
        </tr>
        <tr>
          <td>Keywords:</td>
          <td title="{{ resource.dataEntry.variable.keyword.full_path }}">
            {{ resource.dataEntry.variable.keyword.value }}</td>
        </tr>
        <tr>
          <td>Thesaurus:</td>
          <td title="{{ resource.dataEntry.variable.keyword.thesaurus.description }},
{{ resource.dataEntry.variable.keyword.thesaurus.url }}">
            {{ resource.dataEntry.variable.keyword.thesaurus.title }}</td>
        </tr>
        {#          TODO: check if args.all works when data available#}
        {% if resource.dataEntry.datasource.args.all %}
          <tr>
            <td>Datasource args:</td>
            <td>{{ resource.dataEntry.datasource.args }}</td>
          </tr>
        {% endif %}
        {% if resource.dataEntry.datasource.creation %}
          <tr>
            <td>Creation:</td>
            <td>{{ resource.dataEntry.datasource.creation }}</td>
          </tr>
        {% endif %}
        {% if resource.dataEntry.datasource.encoding %}
          <tr>
            <td>Encoding:</td>
            <td>{{ resource.dataEntry.datasource.encoding }}</td>
          </tr>
        {% endif %}
        <tr>
          <td>Datatype:</td>
          <td title="{{ resource.dataEntry.datasource.datatype.description }}">
            {{ resource.dataEntry.datasource.datatype.name }}</td>
          {#                {{ resource.dataEntry.datasource.datatype.name }}</td>#}
        </tr>
        {% if resource.dataEntry.datasource.temporal_scale %}
          <tr>
            <td>Temporal resolution:</td>
            <td>{{ resource.dataEntry.datasource.temporal_scale.resolution }}</td>
          </tr>
          <tr>
            <td>Observation start:</td>
            <td>{{ resource.dataEntry.datasource.temporal_scale.observation_start }}</td>
          </tr>
          <tr>
            <td>Observation end:</td>
            <td>{{ resource.dataEntry.datasource.temporal_scale.observation_end }}</td>
          </tr>
          <tr>
            <td>Support:</td>
            <td>{{ resource.dataEntry.datasource.temporal_scale.support }}</td>
          </tr>
        {% endif %}
        {% if resource.dataEntry.datasource.spatial_scale %}
          <tr>
            <td>Spatial extent:</td>
            <td>{{ resource.dataEntry.datasource.spatial_scale.extent }}</td>
          </tr>
          <tr>
            <td>Spatial resolution:</td>
            <td>{{ resource.dataEntry.datasource.spatial_scale.resolution }}</td>
          </tr>
          <tr>
            <td>Spatial support:</td>
            <td>{{ resource.dataEntry.datasource.spatial_scale.support }}</td>
          </tr>
        {% endif %}
        <tr>
          <td>Embargo (end date):</td>
          <td>{{ resource.dataEntry.embargo }} ({{ resource.dataEntry.embargo_end }})</td>
        </tr>
        <tr>
          <td>Puclication date:</td>
          <td>{{ resource.dataEntry.publication }}</td>
        </tr>
        {% if resource.dataEntry.datasource.lastupdate %}
          <tr>
            <td>Last update:</td>
            <td>{{ resource.dataEntry.datasource.lastupdate }}</td>
          </tr>
        {% endif %}
        <tr>
          <td>UUID:</td>
          <td>{{ resource.dataEntry.uuid }}</td>
        </tr>
        <tr>
          <td>Citation:</td>
          <td>{{ resource.dataEntry.citation }}</td>
        </tr>
        {#         <p>CreationDate: <strong>{{resource.creationDate}}</strong></p>#}
        {#         <p>Description: <strong>{{resource.description}}</strong></p>#}
        {% comment %}<button class="acc-btn-info-dialog">
         <a href="../../resources/{{resource.id}}" class="acc-info-dialog"download>Access</a>
         </button> {% endcomment %}
        {% comment %}         <button class="acc-tmp-btn" onclick="window.location.href='../../resources/{{resource.id}}'">
            Access
          </button>{% endcomment %}
        {#        </div>#}
        </tr>
        <!-- access button -->
        {#   <a href="../../resources/{{resource.id}}" class="acc-btn">Access</a>#}

        <!-- edit permissions button -->
        <tr>
          <td>
            <a href="{% url 'author_manage:profile' %}my-resources/{{ resource.id }}-edit-users-permissions"
               class="edit-perm w3-btn w3-blue"><strong>Edit Permissions</strong></a>
          </td>

          <td>
            {% if resource in deletion_requested %}
              <a href="#cancel-deletion-request-{{ resource.id }}" class="cancel-del-req"> Cancel Deletion Request </a>

              <!-- modal dialog for canceling deletion request (when such exists) -->

              <div id="cancel-deletion-request-{{ resource.id }}" class="modalDialog">
                <div>
                  <a href="" title="Close" id="x"> x </a>
                  <form action="{% url 'author_manage:cancel-delete-request' resource.id %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                      <p> Are you sure you want to <strong>cancel</strong> the deletion request for resource:
                        <strong>{{ resource.name }}</strong>?
                      </p>
                      <br>
                      <input type="submit" id="no" value="yes, cancel request">
                      <a href="" title="Close" id="close"> Close </a>
                    </div>
                  </form>
                </div>
              </div>
              <br>
            {% else %}

              <!-- the admin has the right to delete his resource without request -->
              {% if is_admin %}
                {% comment %} TODO: Delete request is not working. Only needed for admin
   <a href="#delete-resource-{{resource.id}}" class="delete-btn"> Delete </a>

   <!-- modal dialog for deleting a resource (accessible only for the admin) -->
   <div id="delete-resource-{{resource.id}}" class="modalDialog">
      <div>
         <a href="" title="Close" id="x"> x </a>
         <form action="{% url 'author_manage:delete-resource' resource.id %}" method="post">
            {% csrf_token %}
            <div class = "row">
               <p> Are you sure you want to <strong>delete</strong> the resource
                  <strong>{{resource.name}}</strong>?
               </p>
               <br>
            </div>
            <div class="row">
               <label for="descr">Message: </label><br><br>
               <textarea id="descr" name = "descr" placeholder="optional" maxlength="250" cols = "51" rows = "7"></textarea>
            </div>
            <input id="no" type="submit" value="Yes, delete resource">
            <a href="" title="Close" id="close"> Close </a>
         </form>
      </div>
   </div>
{% endcomment %}
                <!-- the regular user must send a deletion request -->
              {% else %}
                <a href="#send-deletion-request-{{ resource.id }}" class="delete-btn"> Delete </a>
              {% endif %}

              <!-- modal dialog for sending a deletion request -->
              {% comment %}<div id="send-deletion-request-{{resource.id}}" class="modalDialog">
      <div>
         <a href="" title="Close" id="x"> x </a>
         <form action="{% url 'author_manage:send-delete-request' resource.id %}" method="post">
            {% csrf_token %}
            <div class = "row">
               <p> Are you sure you want to send a request for <strong>deletion</strong> of resource:
                  <strong>{{resource.name}}</strong>?
               </p>
               <br>
            </div>
            <div class="row">
               <label for="descr">Message: </label><br>
               <textarea id="descr" name = "descr" placeholder="optional" maxlength="250" cols = "51" rows = "7"></textarea>
            </div>
            <input id="no" type="submit" value="Yes, request deletion">
            <a href="" title="Close" id="close"> Close </a>
         </form>
      </div>
   </div>{% endcomment %}
            {% endif %}
          </td>
        </tr>
      </table>
      </p>
    {% endfor %}
  </div>
{% endblock %}

author_manage/templates/author_manage/upload_persons.html
{% extends add-new-resource.html %}

{% block wizard %}
  <form method="get" name="advancedfilterform">
    <div class="respo-padding-64 respo-medium respo-text-grey" style="font-weight:bold">
        {{ myFilter.form.as_p }}


      <button class="btn btn-primary" type="submit">Search</button>

{#      <a onclick="filter_pagination({{ i }})">{{ i }}</a>#}

{#        <input type="submit" />#}
    </div>
</form>
  <p>bla</p>
{% for obj in selection %}
    {{ obj.variable }} - ${{ obj.license }}<br />
{% endfor %}
{% endblock %}