author_manage/urls.py
from django.urls import path
# from author_manage import views
from django.urls.conf import re_path
from author_manage.admin import resource_manager
from author_manage.admin import user_manager
from author_manage.views import *

# for security reasons all urls are accessible only for logged in users

app_name = 'author_manage'  # jm

urlpatterns = [

    # entry point to the web site, home page
    path('', HomeView.as_view(), name='home'),

    # pages, accessible only for the admin - for managing resources/users
    re_path(r'^resource-manager/', resource_manager.urls),
    re_path(r'^user-manager/', user_manager.urls),

    # profile page, where the user can change his name/see his current access requests
    # the admin can additionally see his current deletion requests
    re_path(r'^profile/$', ProfileView.as_view(), name='profile'),

    # subpage of the profile page, where the user can see all the resources that he owns
    re_path(r'^profile/my-resources/$', MyResourcesView.as_view(), name='my-resources'),

    # for every resource that a user owns, he has the option to edit its permissions
    # initially only the users that have ANY permissions about this resource are displayed
    re_path(r'^profile/my-resources/(?P<resourceid>\d+)-edit-users-permissions/$', PermissionEditingView.as_view(),
            name='edit permissions'),

    # the user has also the option to search for a user, who does not have any permission about
    # this resource to this point, and grant him such
    re_path(r'^profile/my-resources/(?P<resourceid>\d+)-edit-users-permissions/search$',
            PermissionEditingViewSearch.as_view(), name='edit permissions searching for user'),

    # subpage for adding a new resource
    re_path(r'^profile/my-resources/add-new-resource/$', AddNewResourceView.as_view(), name='add-new-resource'),

    # subpage for editing first and/or last name; can not be null
    re_path(r'^profile/edit-name/$', EditNameView.as_view(), name='edit-name'),

    # page for displaying all resources in the portal
    # the user sees 'access' button only if he is privileged to access the resource
    # otherwise he has the option to send an access request
    re_path(r'^resources-overview/$', ResourcesOverview.as_view(), name='resources-overview'),

    # search function in case the resources in the portal are too many
    re_path(r'^resources-overview/search$', ResourcesOverviewSearch.as_view(), name='search-resources'),

    # url for accessing a resource (download function)
    re_path(r'^resources/(?P<resourceid>\d+)$', OpenResourceView.as_view(), name='open resources'),

    # urls for sending/canceling an access request
    re_path(r'^send-access-request/(?P<resourceid>\d+)$', SendAccessRequestView.as_view(), name='send-access-request'),
    re_path(r'^cancel-access-request/(?P<resourceid>\d+)$', CancelAccessRequest.as_view(),
            name='cancel-access-request'),

    # urls for approving/denying an access request; accessible only if requestid
    # is valid and the current user has rights too handle the request
    re_path(r'^approve-access-request/(?P<requestid>\d+)$', ApproveAccessRequest.as_view(),
            name='approve-access-request'),
    re_path(r'^deny-access-request/(?P<requestid>\d+)$', DenyAccessRequest.as_view(), name='deny-access-request'),

    # urls for sending/canceling a deletion request
    re_path(r'^send-deletion-request/(?P<resourceid>\d+)$', SendDeletionRequestView.as_view(),
            name='send-delete-request'),
    re_path(r'^cancel-deletion-request/(?P<resourceid>\d+)$', CancelDeletionRequestView.as_view(),
            name='cancel-delete-request'),

    # urls for approving/denying a deletion request; accessible only if requestid
    # is valid and the current user has rights too handle the request
    re_path(r'^approve-deletion-request/(?P<requestid>\d+)*$', ApproveDeletionRequest.as_view(),
            name='approve deletion request'),
    re_path(r'^deny-deletion-request/(?P<requestid>\d+)$', DenyDeletionRequest.as_view(),
            name='deny deletion request'),

    # url for deleting a resource, accessible only for the admin
    re_path(r'^delete-resource/(?P<resourceid>\d+)*$', DeleteResourceView.as_view(), name='delete resource'),

]

heron/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path as url

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.views.generic.base import RedirectView
from vfwheron import views as vfw_views
from django.views.i18n import JavaScriptCatalog

# TODO: for JS translations see:
#  https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#note-on-performance
urlpatterns = [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^$', RedirectView.as_view(url='home/', permanent=False)),
    path('home/', include('vfwheron.urls')),
    path('admin/', admin.site.urls),
    path('legals', vfw_views.Legals.as_view(), name='legals'),
    path('workspace/', include('wps_gui.urls', namespace='wps_gui')),
    path('monitor/', include('heron_monitor.urls', namespace='heron_monitor')),
    path('visual/', include('heron_visual.urls', namespace='heron_visual')),
    path('upload/', include('upload.urls', namespace='upload')),
    path('download/<str:name>', vfw_views.DownloadView.as_view()),
    path('admin/doc/', include('django.contrib.admindocs.urls')),  # from wps_workflow
    path('user/', include('author_manage.urls', namespace='author_manage')),
    # path('__debug__/', include(debug_toolbar.urls))  # only when debug toolbar is installed!
]

handler404 = 'vfwheron.views.error_404_view'

# This is just to test the upload in the development environment
if settings.DEBUG and settings.DEBUG != '':
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vfwheron/urls.py
from django.conf.urls import include
from django.urls import path, re_path

from heron import settings
from . import views


app_name = 'vfwheron'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('watts_login', views.LoginView.as_view(), name='watts_login'),
    path('help', views.HelpView.as_view(), name='help'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    # re_path(r'^geoserver/(?P<service>[\w{3,4}]+)/(?P<layer>[\w]+)/(?P<bbox>[\-.,\d]+)/(?P<srid>[\d]{4,5})$',
    #     views.GeoserverView.as_view()),
    path('geoserver/<str:service>/<str:layer>/<str:bbox>/<int:srid>', views.GeoserverView.as_view()),
    path('togglelang', views.ToggleLanguageView.as_view(), name='togglelang'),
    path('failedlogin', views.FailedLoginView.as_view(), name='failedlogin'),
    path('datasetdownload', views.DatasetDownloadView.as_view(), name='datasetdownload'),
    path('entries_pagination', views.entries_pagination, name='entries_pagination'),
    path('short_info_pagination', views.short_info_pagination, name='short_info_pagination'),
    path('advanced_filter', views.advanced_filter),
    # path('quick_filter', views.QuickFilter.as_view(), name='quick_filter'),
    path('quick_filter_args/<selection>', views.QuickFilterResults.as_view(), name='quick_filter_args'),
    # url(r'^advanced_filter$', views.filter_entries),
    # addresses for fetch:
    # url(r'^previewplot/id(db[\d]{1,6}|wps[\d]{1,6})$', views.PreviewPlot.as_view()),
    # url(r'^showinfo/id(db[\d]{1,6}|wps[\d]{1,6})$', views.ShowInfo.as_view()),
    # addresses for ajax:
    path('previewplot', views.previewplot, name='previewplot'),
    path('show_info', views.show_info, name='show_info'),
    path('workspace_data', views.workspace_data, name='workspace_data'),
]

# use watts for authorization, or django for development environment
if settings.ON_VFW_SERVER:
    urlpatterns.append(re_path(r'^rsp/', include('watts_rsp.urls')))
else:
    urlpatterns.append(path('', include('django.contrib.auth.urls')))

vfwheron/views.py
import ast
import csv
import datetime
import json
import sys

import pandas as pd
import requests
from django.contrib.gis.db.models.aggregates import Extent
from django.core.exceptions import EmptyResultSet, FieldError
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.utils.timezone import make_aware
from pyzip import PyZip

import matplotlib as mpl
import urllib
from collections import defaultdict
from django.conf import settings
from django.contrib.auth import logout
from django.http import StreamingHttpResponse, QueryDict
from django.http.response import JsonResponse, HttpResponse, Http404, FileResponse
from django.shortcuts import redirect, render
from django.utils import translation, timezone
from django.views import View
from django.views.generic import TemplateView
from django.contrib import messages
from future.builtins import isinstance

import vfwheron
from author_manage.views import MyResourcesView
from heron.settings import LOCAL_GEOSERVER, DEMO_VAR, DATA_DIR

from vfwheron.geoserver_layer import create_layer, get_layer, delete_layer, test_geoserver_env
from vfwheron.previewplot import get_plot_from_db_id, get_bokeh_std_fullres, format_label
from wps_gui.models import WpsResults
from .data_tools import __get_timescale, fill_data_gaps, precision_to_minmax, is_data_short, DataTypes, \
    __get_axis_limits, __reduce_dataset
from .forms import QuickFilterForm

mpl.use('Agg')

from django.contrib.gis.geos import Polygon
from .query_functions import get_bbox_from_data
# from .filter import QuickFilter
from .filters import NMPersonsFilter
from .models import Entries

import logging
from pathlib import Path
# for debugging:
from time import time

# Create your views here.
"""

"""
logger = logging.getLogger(__name__)



# from Django doc about session: If SESSION_EXPIRE_AT_BROWSER_CLOSE is set to True, Django will use browser-length
# cookies – cookies that expire as soon as the user closes their browser. Use this if you want people to have to log in
# every time they open a browser.
def expressive_layer_name(user: object) -> str:
    """
    Build an expressive name for the layer o the geoserver
    :param user:
    :return: String of user id + username + "_layer"
    """
    namestring = str(user.id) + "_"
    if user.first_name and user.last_name:
        namestring += (user.first_name + "_" + user.last_name)
    else:
        namestring += user.username.translate({ord(c): "_" for c in "!@#$%^&*()[]{};:,./<>?\|`=+"})

    return namestring + "_layer"


class HomeView(TemplateView):
    """
    Template View to bring the necessary variables for the startup to the template
    """
    template_name = 'vfwheron/home.html'

    # Before you make migrations
    # Menu = Menu().get_menu()
    # JSON_Menu = json.dumps(Menu['client'])
    data_layer = 'amsterdam_border'

    # if not dataExt:
    data_ext = [645336.034469495, 6395474.75106861, 666358.204722283, 6416613.20733359]

    # IMPORTANT! Don't use "-" in geoserver names!!!
    store = 'GetirStore'
    workspace = 'Getir'
    unlocked_embargo = []

    try:
        test_geoserver_env(store, workspace)

    except:
        print('\033[91mno geoserver\033[0m ', sys.exc_info()[0])

    # TODO: Test with users if this makes any sense
    def __set_layer_name(self):
        """
        Set name for layer in geoserver according to username or as admin_layer.
        """
        if self.request.user.is_authenticated:
            if self.request.user.is_superuser:
                self.data_layer = 'amsterdam_border'
            else:
                self.data_layer = expressive_layer_name(self.request.user)

    # Put here everything you need at startup and for refresh of 'Home'
    def get_context_data(self, **kwargs: object):
        """
        Collect data needed for startup of V-FOR-WaTer Portal home.

        :param kwargs:
        :return:
        """
        self.__set_layer_name()

        try:
            unblocked_ids = self.request.session['datasets']
        except KeyError:
            unblocked_ids = []
            self.request.session['datasets'] = []

        try:
            if not get_layer(self.data_layer, self.store, self.workspace):
                create_layer(self.request, self.data_layer, self.store, self.workspace)
            else:
                # TODO: don't do that in production! That's just for development to make sure geoserver is updated
                #  after restart of django
                delete_layer(self.data_layer, self.store, self.workspace)
                create_layer(self.request, self.data_layer, self.store, self.workspace)
        except:
            self.data_layer = 'Error: Found no geoserver!'
            print('Still no geoserver: ', sys.exc_info()[0])

        self.data_ext = get_bbox_from_data()

        context = quick_filter_defaults(self)

        return {'dataExt': self.data_ext, 'data_layer': self.data_layer,
                'messages': messages.get_messages(self.request), 'unblocked_ids': unblocked_ids,
                **context}


class TestView(View):

    def get(self, request):
        print('request: ', request)
        return JsonResponse({'answer': 'läuft'})


class Echo:
    """
    An object that implements just the write method of the file-like interface.
    """

    def write(self, value):
        """
        Write the value by returning it, instead of storing in a buffer.
        """
        return value


def get_accessible_data(request: object, requested_ids: list) -> (list, list):
    """
    Use request object to check if user has read access to a list of data (entries_id). Output is a list with
    accessible data and a second list with inaccessible data.

    :param request:
    :param requested_ids:
    :return: accessible_ids, error_ids
    """
    if isinstance(requested_ids, int):
        requested_ids = [requested_ids]
    elif isinstance(requested_ids, str):
        requested_ids = [int(requested_ids)]
    # first get datasets without embargo / open for for everyone
    accessible_data = list(Entries.objects.
                           values_list('id', flat=True).filter(pk__in=requested_ids, embargo=False))
    # check if the user wanted more and is authenticated. If yes check if user has access and get the rest
    if len(requested_ids) > len(accessible_data) and request.user.is_authenticated:
        accessible_embargo_datasets = list(set(requested_ids) & set(request.session['datasets']))  # intersect sets
        accessible_data.extend(accessible_embargo_datasets)
    # check if there is still data not accessible and create error for these
    error_list = list(set(requested_ids) - set(accessible_data))
    return {'open': accessible_data, 'blocked': error_list}


def get_dataset(s_id: int) -> object:
    """

    :param s_id: ID in metacatalob
    :return:
    """
    entry_type = Entries.objects.filter(pk=s_id).values_list('datasource__datatype__name', flat=True)[0]

    # build string of values for django query
    type_values = {'generic_1d_data': ['index', 'value', 'precision'],
                   'generic_2d_data': ['index', 'value1', 'value2', 'precision1', 'precision2'],
                   'generic_geometry_data': ['index', 'geom', 'srid'],
                   'geom_timeseries': ['tstamp', 'geom', 'srid'],
                   'timeseries_1d': ['tstamp', 'value', 'precision'],
                   'timeseries_2d': ['tstamp', 'value1', 'value2', 'precision1', 'precision2']}
    db_values = type_values[entry_type]

    query_values = []
    for value in db_values:
        query_values.append('{}__{}'.format(entry_type, value))

    query_filter = {entry_type: s_id}
    return Entries.objects.filter(**query_filter).values_list(*query_values)


class DatasetDownloadView(TemplateView):
    """

    """

    def get(self, request):
        """

        :param request:
        :type request:
        :return:
        :rtype:
        """
        store = HomeView.store  # 'new_vforwater_gis'
        workspace = HomeView.workspace  # 'CAOS_update'
        test_geoserver_env(store, workspace)


        if 'csv' in request.GET:
            # if 'download_data' in request.GET:
            s_id = json.loads(request.GET.get('csv'))
            accessible_data = get_accessible_data(request, s_id)
            error_list = accessible_data['blocked']
            accessible_data = accessible_data['open']

            if len(accessible_data) > 0:
                # TODO: There are 3 Solutions to get data from the different tables.
                #  Solution 1 produces many None fields, hence is discarded.
                #  Solution 2 makes a query from 'Entries' to get datatype and builds another query from 'Entries'
                #  according to the result.
                #  Solution 3 gets the datatype and 'eval' a query for the respective table.
                #  Decide if solution 2 or 3 is better.
                #  Check if results are the right datasets!!!
                #  (Unused solutions deleted. Check commit from Sept 3, 2020)

                # Solution 2:
                # ===========
                rows = get_dataset(accessible_data[0])

                pseudo_buffer = Echo()
                writer = csv.writer(pseudo_buffer)
                response = StreamingHttpResponse((writer.writerow(row) for row in rows), content_type="text/csv")
                response['Content-Disposition'] = 'attachment; filename="somefilename.csv"'
            return response

        if 'shp' in request.GET:
            s_id = request.GET.get('shp')
            accessible_data = get_accessible_data(request, s_id)
            error_list = accessible_data['blocked']
            accessible_data = accessible_data['open']

            if len(accessible_data) > 0:
                layer_name = 'shp_{}_{}_{}'.format(request.user, request.user.id, s_id)
                srid = 4326

vfwheron/templates/vfwheron/advanced_filter.html
{#{% extends "vfwheron/select_data.html" %}#}

{#{% load static %}#}
{#{% load i18n %}#}
{#{% get_current_language as LANGUAGE_CODE %}#}
{% comment %}

<form method="post" novalidate>
  {% csrf_token %}
  <table border="1">
    {{ form }}
  </table>
  <button type="submit">Submit</button>
</form>

{% endcomment %}
{#{% include "vfwheron/filter_entries.html" %}#}
{#{% block advanced_filter %}#}
<form method="get" name="advancedfilterform" id="advancedfilter-form">
    <div class="respo-padding-64 respo-medium respo-text-grey" style="font-weight:bold">
{#        {{ advFilter.form }}#}
{#        {{ advFilter.form.as_p }}#}
{% for obj in advFilter.form %}
   {{ obj.name }}: {{ obj }} <br />
{#   <select onchange="console.log('bla')" {{ obj.name }}: {{ obj }}></select> <br />#}
{% endfor %}
  {{ advFilter.embargo }}
      <button class="btn btn-primary" type="submit">Search</button>

{#      <a onclick="filter_pagination({{ i }})">bla{{ i }}</a>#}

{#        <input type="submit" />#}
    </div>
</form>
<p>Selection:</p>
{% for obj in selection.qs %}
    {{ obj.variable }} - ${{ obj.license }}<br />
{% endfor %}

{#{% endblock %}#}
{% comment %}
 <script>
    $(document).on('submit','#advancedfilter-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "home" %}',
            data:
            {
                task:$("#task").val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
            },
            success:function(){
                  alert('Saved');
                    }
            })
        });
    </script>
{% endcomment %}

vfwheron/templates/vfwheron/failedlogin.html
<!DOCTYPE html>
<html>
<head>
<title>vforwater</title>
</head>
<body>

<h1>Login failed.</h1>
<p><a href="https://portal.vforwater.de/demo/vfwheron/">go back</a></p>

</body>
</html>

vfwheron/templates/vfwheron/help.html
<meta charset="UTF-8">
{% extends "vfwheron/base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load markdown_filter %}

{% block sidebar %}
	{% include 'vfwheron/static_sidebar.html' %}
{% endblock sidebar %}

{% block content %}

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>{% trans "Help" %}</h1>
      <p>{% trans "Welcome! This site is still under construction" %}</p>
  </div>
</div>
<div class="row">
    <a class='w3-hover-none' style='height:103px' id='search_box'><input type='search' value='' placeholder='Search ...' style='height:26px; font-size:70%;'></a>
    <a href='#' class='w3-hover-white' style='height:103px' id='search_but' onclick='search_close()'><i class='fa fa-search fa-fw'></i></a>

</div>
<div class="row">
  {% for key,value in context.items %}
  <p>{{ value|markdownify|safe }}<p>
  {% endfor %}
</div>

{% endblock %}

vfwheron/templates/vfwheron/home.html
<meta charset="UTF-8">
<meta name="description" content="Portal to share and use hydrological data">
<meta name="keywords" content="Hydrologie, Hydrology, GIS, Portal, eScience, VRE, VFU, virtual research environment, Virtuelle Foschungsumgebung">
<meta name="author" content="Elnaz Azmi, Marcus Strobl">

{% extends "vfwheron/base.html" %}
{% load static %}
{% load i18n %}

{% block sidebar %}
	{% include 'vfwheron/base_sidebar.html' %}
{% endblock sidebar %}

{% block content %}
   <!-- Tab links -->
<div class="tab">
  <button class="tablinks" onclick="toggleMapTableFilter(event, 'Map')" id="defaultMapTab">{% trans "Map" %}
  </button>
  <button class="tablinks" onclick="toggleMapTableFilter(event, 'paginationTable'); filter_pagination()">{% trans "Table" %}
  </button>
</div>

<!-- Tab content -->
<div id="Map" class="tabcontent">
  {% include 'vfwheron/map.html' %}
</div>

<div id="paginationTable" class="tabcontent">
  {% include 'vfwheron/entrieslist.html' %}
</div>

<!-- Login alert -->
  {% if messages.alert %}
     <script>alert("Login failed.");</script>

     {% comment %}
     {# todo: nice message window #}
     <ul class="messages">
     {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
     {% endfor %}
     </ul>
     {% endcomment %}
  {% endif %}



<script>
// Get the element with id="defaultMapTab" and click on it
document.getElementById("defaultMapTab").click();
</script>
{% endblock %}

vfwheron/templates/vfwheron/logo.html
{% load static %}

 <div class="w3-container w3-row">
   <div class="w3-col s4">
     <img src="{% static 'vfwheron/images/logo_main.png' %}" style="width:200px"><br>
   </div>
 </div>

vfwheron/templates/vfwheron/sidemenu.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<head>
  <script src="{% static 'vfwheron/js/sidebar.js' %}" type="text/javascript"></script>
  <script src="{% static 'vfwheron/js/FileSaver.js' %}" type="text/javascript"></script>
</head>

<body>
<!--   Sidemenu -->
<nav class="w3-sidenav w3-white w3-animate-right w3-hide-large"
     style="z-index:3; width:160px; height:280px; right: 0; margin-top: 80px; display:none" id="mySidemenu">
  <a href="#" class="w3-padding-8 w3-hide-large w3-dark-grey w3-hover-black" onclick="Sidemenu_close()"
     title="close menu"><i class="fa fa-remove fa-fw"></i>{% trans "  Close Menu" %}</a>
  <div id="accordion">
    <br>
    <a href="{% url 'vfwheron:home' %}" class="w3-hover-blue"><i class="fa fa-home fa-fw"></i>{% trans "  Home" %}</a>
    <a href="{% url 'wps_gui:home' %}" class="w3-hover-blue"><i class="fa fa-wrench fa-fw"></i>{% trans "  Workspace" %}
    </a>
    {% comment %}<a href="{% url 'heron_monitor:home' %}" class="w3-hover-blue"><i
            class="fa fa-eye fa-fw"></i>{% trans "  Monitor" %}</a>{% endcomment %}
    {% comment %}<a href="{% url 'heron_visual:home' %}" class="w3-hover-blue"><i
            class="fa fa-bar-chart fa-fw"></i>{% trans "  Visualisation" %}</a>{% endcomment %}
    <div class="w3-dropdown-hover w3-transparent">
      <a class="w3-hover-blue ">
        <i class="fa fa-external-link fa-fw"></i>{% trans "  Help" %}<i class="fa fa-caret-down fa-fw"></i>
        <div class="w3-dropdown-content w3-padding-left w3-pale-blue" style="right:0">
          <a href="{% url 'vfwheron:help' %}" class="w3-hover-blue">
            <i class="fa fa-book fa-fw"></i>{% trans "  Portal Help" %}
          </a>
          <a target="_blank" href="https://vforwater.de" style="text-decoration:none" class="w3-hover-blue">
            <i class="fa fa-sitemap fa-fw"></i>{% trans "  Web Site" %}
          </a>
          <a target="_blank" href={{ VFW_SERVER|add:"/doc" }} style="text-decoration:none" class="w3-hover-blue">
            <i class="fa fa-book fa-fw"></i>{% trans "  Documentation" %}
          </a>
          <a target="_blank" href="https://github.com/VForWaTer/pleasant" style="text-decoration:none"
             class="w3-hover-blue">
            <i class="fa fa-code fa-fw"></i>{% trans "  Source Code" %}
          </a>
        </div>
      </a>
    </div>
    <!--{#        <a href="{% url 'vfwheron:login' %}" class="w3-hover-red"><i class="fa fa-user fa-fw"></i>{% trans " Log in" %}</a>#} -->
    {% if user.is_authenticated %}
      <div class="w3-dropdown-hover w3-transparent">
        <a class="w3-hover-white ">
          <i class="fa fa-user fa-fw"></i>
          {% if user.first_name %}
            {{ user.first_name | capfirst }}
          {% else %}
            {{ user.username | capfirst }}
          {% endif %}
          <i class="fa fa-caret-down fa-fw"></i>

          <div class="w3-dropdown-content" style="right:0">
            <a class="w3-hover-blue " href="{% url 'author_manage:profile' %}">{% trans "Profile" %}</a>
{#            <a class="w3-hover-blue "#}
{#               href="{% url 'author_manage:resources-overview' %}">{% trans "Resource Overview" %}</a>#}
            <a href="#" class="w3-hover-blue">
              <form action="{% url 'vfwheron:logout' %}" method="post"> {% csrf_token %}
                <input class="w3-btn-simple" type="submit" name="logout" value="Logout"/>
              </form>
            </a>
          </div>
        </a>
      </div>
      {% if user.is_staff %}  <!-- admin stuff goes here -->
        <div class="w3-dropdown-hover w3-transparent">
          <a class="w3-hover-red">
            <i class="fa fa-beer fa-fw"></i> Admin<i class="fa fa-caret-down fa-fw"></i>
            <div class="w3-dropdown-content" style="right:0">
              <a class="w3-hover-red nav" value="ManageUsers" title="Manage Users">Manage Users</a>
              <a class="w3-hover-red nav" value="ManageSomething" title="Manage Something">Manage Something</a>
              <!--                    <option class="w3-hover-blue nav" value="test" title="test"><a class="w3-hover-blue nav" href="#">test</a></option> -->
            </div>
          </a>
        </div>
        <!-- is_staff -->
      {% endif %}

      <!-- is_authenticated -->
    {% else %}
      <a class="w3-hide-small w3-right w3-hover-white">
        <form class="w3-hover-white " action="{% url 'vfwheron:watts_login' %}" method="post"> {% csrf_token %}
          <i class="fa fa-user fa-fw"></i>
          <input class="w3-btn-simple " type="submit" name="login" value='{% trans "  Login" %}'/>
        </form>
      </a>
    {% endif %}
  </div>
</nav>

{#  Overlay effect when opening sidenav on small screens #}
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="Sidemenu_close()" style="cursor:pointer"
     title="close side menu" id="mySidemenuOverlay"></div>

</body>

vfwheron/templates/vfwheron/workflow.html
<meta charset="UTF-8">

{% extends "vfwheron/base.html" %}
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block title %}- Heron WPS{% endblock %}

{% block sidebar %}
 	{% include 'vfwheron/wps_sidebar.html' %}
{% endblock sidebar %}

{% block content %}

{#<script type="text/javascript">$(document).ready(function(){$("#wpstool").attr("src", "{% url 'wps_workflow:index' %}")})</script>#}
<!--  <div class="row"> -->
		<div class="col-md-8 col-md-offset-2" id="wpscontainer">
			<iframe id="wpstool" src="{% url 'wps_workflow:index' %}"
				frameBorder="0" height="80%" width="100%"
				style="margin-top: -20px; -moz-border-radius: 0; -webkit-border-radius: 0; border-radius: 0; height: calc(80% - 29px);" />
		</div>
<!-- </div> -->
{% endblock %}